8009154: Missing cast in method reference bridge leads to NoSuchMethodError
Summary: Missing cast in generated method reference bridge
Reviewed-by: rfield, jjg